// Punto de entrada del chequeo del mapa de impacto (scripts/check-map.mjs).
// Sólo reexporta el código real: toda la lógica de aserción vive en el .mjs.
export {
  normalizeLocalityName,
  LOCALITY_ALIASES,
  matchLocality,
  buildLocalityMap,
  provinceTotals,
  localityRows,
  topLocalities,
  computeHeatClasses,
  heatColor,
  HEAT_COLORS,
  NO_DATA_COLOR,
  MAX_HEAT_CLASSES,
  HEAT_RAMP,
  NO_DATA_TOKEN,
  NO_DATA_LABEL,
  BUBBLE_RAMP,
  BUBBLE_RAMP_TOKENS,
  BUBBLE_OUTLINE,
  rampIndices,
  themeColor,
  featureAnchor,
  departmentTotals,
  matchDepartment,
  bubbleRadius,
  buildBubbles,
  bubbleLegendValues,
  separateBubbles,
  BUBBLE_MAX_OVERLAP,
  BUBBLE_MAX_SHIFT,
  placeBubbleLabels,
  labelBoxSize,
  BUBBLE_LABEL_SIZE,
  pickDepartmentAnchor,
  boxesOverlap,
  boxTouchesCircle,
  BUBBLE_MIN_RADIUS,
  BUBBLE_MAX_RADIUS,
} from '@/lib/localityMap';
export {
  GEO_AREAS,
  GEO_POINTS,
  GEO_DEPARTMENTS,
  GEO_VIEWBOX,
  GEO_SOURCE,
} from '@/lib/geo/formosa.generated';
export { localityStatsSchema } from '@/schemas/localityStats';
export {
  clampView,
  zoomAt,
  panBy,
  centerOn,
  toScreen,
  toMap,
  inverseScale,
  bubblesOnScreen,
  lerpView,
  isVisible,
  MIN_ZOOM,
  MAX_ZOOM,
  IDENTITY_VIEW,
} from '@/lib/mapZoom';
