// Punto de entrada del chequeo del mapa de impacto (scripts/check-map.mjs).
// Sólo reexporta el código real: toda la lógica de aserción vive en el .mjs.
export {
  normalizeLocalityName,
  LOCALITY_ALIASES,
  matchLocality,
  buildLocalityMap,
  provinceTotals,
  localityRows,
  topLocalities,
  themeColor,
  departmentTotals,
  matchDepartment,
  HEAT_STOPS,
  HEAT_GRADIENT_CSS,
  PROVINCE_FILL,
  HEAT_SIGMA,
  HEAT_CUTOFF,
  HEAT_MIN_WEIGHT,
  heatWeight,
  heatAlpha,
  buildColorTable,
  buildHeatPoints,
  heatValueRange,
  computeHeatField,
  heatAt,
  colorizeHeatField,
  placeBubbleLabels,
  labelBoxSize,
  boxesOverlap,
  boxTouchesCircle,
} from '@/lib/localityMap';
export {
  GEO_AREAS,
  GEO_POINTS,
  GEO_DEPARTMENTS,
  GEO_VIEWBOX,
  GEO_SOURCE,
} from '@/lib/geo/formosa.generated';
export { localityStatsSchema } from '@/schemas/localityStats';
export {
  clampView,
  zoomAt,
  panBy,
  centerOn,
  toScreen,
  toMap,
  inverseScale,
  markersOnScreen,
  lerpView,
  isVisible,
  MIN_ZOOM,
  MAX_ZOOM,
  IDENTITY_VIEW,
} from '@/lib/mapZoom';
export {
  chooseFullscreenMode,
  nextFocusIndex,
  scrollbarCompensation,
  escapeAction,
} from '@/lib/fullscreenMode';
